### ISSUE TITLE
Network Variable error

### ISSUE THREAD

**Issue by Boringness** [TheLimeGlass/Skungee#12]
```
02.07 02:30:25 [Server] INFO BotSpam issued server command: /sk reload modreq
02.07 02:30:25 [Server] ERROR #!#! 
02.07 02:30:25 [Server] ERROR #!#! [Skript] Severe Error:
02.07 02:30:25 [Server] ERROR #!#! Could not load modreq.sk
02.07 02:30:25 [Server] ERROR #!#! 
02.07 02:30:25 [Server] ERROR #!#! Something went horribly wrong with Skript.
02.07 02:30:25 [Server] ERROR #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
02.07 02:30:25 [Server] ERROR #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
02.07 02:30:25 [Server] ERROR #!#! Here is full list of them:
02.07 02:30:25 [Server] ERROR #!#! skript-ping skRayFall (http://sk.rayfall.net/) SkriptJSON skript-mirror Vixio (http://vixio.space) Skungee TuSKe (github.com/Tuke-Nuke/TuSKe) skUtilities (https://tim740.github.io/) SkQuery Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/) Reqn Umbaska 
02.07 02:30:25 [Server] ERROR #!#! We could not identify which of those are specially related, so this might also be Skript issue.
02.07 02:30:25 [Server] ERROR #!#! You should try disabling those plugins one by one, trying to find which one causes it.
02.07 02:30:25 [Server] ERROR #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
02.07 02:30:25 [Server] ERROR #!#! In that case, you will be given instruction on how should you report it.
02.07 02:30:25 [Server] ERROR #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
02.07 02:30:25 [Server] ERROR #!#! Only if the author tells you to do so, report it as Skript issue (url below)
02.07 02:30:25 [Server] ERROR #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
02.07 02:30:25 [Server] ERROR #!#! 
02.07 02:30:25 [Server] ERROR #!#! Stack trace:
02.07 02:30:25 [Server] ERROR #!#! java.lang.NullPointerException
02.07 02:30:25 [Server] ERROR #!#!     at ch.njol.skript.util.Utils.parseInt(Utils.java:512)
02.07 02:30:25 [Server] ERROR #!#!     at ch.njol.skript.expressions.ExprArgument.init(ExprArgument.java:91)
02.07 02:30:25 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:253)
02.07 02:30:25 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
02.07 02:30:25 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:325)
02.07 02:30:25 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:627)
02.07 02:30:25 [Server] ERROR #!#!     at ch.njol.skript.lang.VariableString.newInstance(VariableString.java:241)
02.07 02:30:25 [Server] ERROR #!#!     at me.limeglass.skungee.spigot.elements.expressions.ExprNetworkVariable.init(ExprNetworkVariable.java:58)
02.07 02:30:25 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:253)
02.07 02:30:25 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
02.07 02:30:27 [Multicraft] Skipped 61 lines due to rate limit (30/s)
02.07 02:30:27 [Server] INFO BotSpam issued server command: /modreq
```

```
on join:
	if network variable {ticket.%player%.reply::ticket} is set:
		send "&8[&c*&8]&7 Your ticket&8(&c%global variable {ticket.%player%.reply.ID::ticket}%&8)&7 has been closed due to %global variable {ticket.%player%.reply::ticket}%"
		delete network variable {ticket.%player%.reply::ticket}
		delete network variable {ticket.%player%.reply.ID::ticket}
		
command /ts [<text>] [<integer>] [<text>]:
	permission: smc.jrmod
	trigger:
		if arg-1 is "close":
			if {ticket.ID::%arg-2%} is set:
				set network variable {_p} to network variable {ticket.player::%arg-2%} parsed as player
				if {_p} is online:
					send "&8[&c*&8]&7 Your ticket&8(&c%global variable {ticket.ID::%arg-2%}%&8)&7 has been closed due to %arg-3%" to {_p} 
				else:
					set network variable {ticket.%global variable {_p}%.reply::ticket} to arg-3
					set network variable {ticket.%global variable {_p}%.reply.ID::ticket} to network variable {ticket.ID::%arg-2%}
					delete network variable {ticket.player::%arg-2%}
					delete network variable {ticket.ID::%arg-2%}
					delete network variable {ticket.location::%arg-2%}
					delete network variable {ticket.time::%arg-2%}
					set network variable {ticket.status::%arg-2%} to "&cClosed"
					delete network variable {ticket.reason::%arg-2%}
					set network variable {accept.%arg-2%} to arg-3
					add 1 to {ticket.id::*}
			else:
				send "&8[&c*&8]&7 Ticket has already been closed"
		if arg-1 is "info":
			if {ticket.ID::%arg-2%} is set:
				send "&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8[ &7&lINFO&8 ]&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-"
				send " &7&l» &7Username&8:&3 %network variable {ticket.player::%arg-2%}%"
				send " &7&l» &7ID&8:&3 %network variable arg-2%"
				send " &7&l» &7Reason&8:&3 %network variable {ticket.reason::%arg-2%}%"
				send " &7&l» &7Time&8:&3 %network variable {ticket.time::%arg-2%}%"
				send "&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-&c&l-&8&l-"
			else:
				send "&8[&c*&8]&7 Invaild ticket ID"
		if arg-1 is "check":
			if {ticket.ID::*} isn't set:
				message "&8[&c*&8] &7No open tickets at this time"
			else:
				send "&8&l>&7 %network variable {ticket.ID::*}%"
			stop
		if arg-1 is "reset":
			delete network variable {ticket.id::*}
		
command /modreq [<text>]:
	trigger:
		set network variable {_ID} to (size of {ticket.id::*})+1
		set network variable {ticket.ID::%network variable {_ID}%} to network variable {_ID}
		set network variable {ticket.player::%network variable {_ID}%} to "%player%"
		set network variable {ticket.location::%{_ID}%} to player's location
		set network variable {ticket.time::%network variable {_ID}%} to "%now%"
		set network variable {ticket.status::%network variable {_ID}%} to "&aOpen"
		set network variable {ticket.reason::%network variable {_ID}%} to arg-1
		send "&8[&c*&8] &7Your ticket has been created staff will assist shortly%nl%&8&l>&7 &7ID&8: &3%global variable {_ID}%"
		
command /goto [<integer>]:
	permission: smc.jrmod
	trigger:
		send "&8[&c*&8]&7 Teleporting to %global variable {ticket.location::%arg-1%}%"
		teleport player to global variable {ticket.location::%arg-1%}
```

**Comment by TheLimeGlass** [comment]
Potentially fixed in next update. The next update completely changed how variables work.
