### ISSUE TITLE
An missing ] in ShutDown effect 

### ISSUE THREAD

**Issue by Tedyst** [TheLimeGlass/Skungee#14]
There is an ] missing in the ShutDown effect.

The full error that does not let any scripts load:
> [07:34:18 ERROR]: #!#! 
[07:34:18 ERROR]: #!#! [Skript] Severe Error:
[07:34:18 ERROR]: #!#! Could not load docker.sk
[07:34:18 ERROR]: #!#! 
[07:34:18 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[07:34:18 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[07:34:18 ERROR]: #!#! and check whether this error has already been reported.
[07:34:18 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[07:34:18 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[07:34:18 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[07:34:18 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[07:34:18 ERROR]: #!#! 
[07:34:18 ERROR]: #!#! Stack trace:
[07:34:18 ERROR]: #!#! ch.njol.skript.lang.SkriptParser$MalformedPatternException: Missing closing bracket ']' [pattern: (stop|shutdown) bungee[[ ]cord] server[s] %strings% [(and|with) [serverinstances] saving %-boolean%]
[07:34:18 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.nextBracket(SkriptParser.java:872)
[07:34:18 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1056)
[07:34:18 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1123)
[07:34:18 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1057)
[07:34:18 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1057)
[07:34:18 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1084)
[07:34:18 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:221)
[07:34:18 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[07:34:18 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:61)
[07:34:18 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:754)
[07:34:18 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:56)
[07:34:18 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:46)
[07:34:18 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:840)
[07:34:18 ERROR]: #!#!     at ch.njol.skript.lang.Loop.<init>(Loop.java:68)
[07:34:18 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:790)
[07:34:18 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:56)
[07:34:18 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:46)
[07:34:18 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:840)
[07:34:18 ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:467)
[07:34:18 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:472)
[07:34:18 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:271)
[07:34:18 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:167)
[07:34:18 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[07:34:18 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143)
[07:34:18 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
[07:34:18 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1194)
[07:34:18 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1006)
[07:34:18 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[07:34:18 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[07:34:18 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[07:34:18 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[07:34:18 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[07:34:18 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[07:34:18 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:776)
[07:34:18 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[07:34:18 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715)
[07:34:18 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618)
[07:34:18 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)

**Comment by TheLimeGlass** [comment]
Have you deleted your syntax.yml and let it regenerate? You can also modify the syntax.yml to include the missing bracket.

**Comment by Tedyst** [comment]
I am pretty sure that I do not save the syntax.yml in my server image(docker), but I'll verify.
