### ISSUE TITLE
Error with network variable syntax

### ISSUE THREAD

**Issue by Vulqa** [TheLimeGlass/Skungee#28]
Hi,

When i reload my script with this code :
```
command /uuid [<text>] [<text>]:
	trigger:
		if argument 1 is "test":
			if argument 2 is set:
				set {_uuid} to network variable {api::users::%arg-2%::uuid}
				message {_uuid}
```
i have this error ( if i put arg-1 instead of arg-2 i have no error ) :
```
[06:29:36 ERROR]: #!#!
[06:29:36 ERROR]: #!#! [Skript] Severe Error:
[06:29:36 ERROR]: #!#! Could not load api.sk
[06:29:36 ERROR]: #!#!
[06:29:36 ERROR]: #!#! Something went horribly wrong with Skript.
[06:29:36 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[06:29:36 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[06:29:36 ERROR]: #!#! Here is full list of them:
[06:29:36 ERROR]: #!#! Skungee TuSKe (github.com/Tuke-Nuke/TuSKe) Skore Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/) SkQuery
[06:29:36 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[06:29:36 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[06:29:36 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[06:29:36 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[06:29:36 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[06:29:36 ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
[06:29:36 ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
[06:29:36 ERROR]: #!#!
[06:29:36 ERROR]: #!#! Stack trace:
[06:29:36 ERROR]: #!#! java.lang.NullPointerException
[06:29:36 ERROR]: #!#!     at ch.njol.skript.util.Utils.parseInt(Utils.java:633)
[06:29:36 ERROR]: #!#!     at ch.njol.skript.expressions.ExprArgument.init(ExprArgument.java:91)
[06:29:36 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:252)
[06:29:36 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[06:29:36 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:324)
[06:29:36 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:638)
[06:29:36 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.newInstance(VariableString.java:242)
[06:29:36 ERROR]: #!#!     at me.limeglass.skungee.spigot.elements.expressions.ExprNetworkVariable.init(ExprNetworkVariable.java:72)
[06:29:36 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:252)
[06:29:36 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[06:29:36 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:502)
[06:29:36 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:836)
[06:29:36 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1564)
[06:29:36 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1560)
[06:29:36 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[06:29:36 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[06:29:36 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[06:29:36 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:984)
[06:29:36 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54)
[06:29:36 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:44)
[06:29:36 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1071)
[06:29:36 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54)
[06:29:36 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:44)
[06:29:36 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1071)
[06:29:36 ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:500)
[06:29:36 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:630)
[06:29:36 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:392)
[06:29:36 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:404)
[06:29:36 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:443)
[06:29:36 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:181)
[06:29:36 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[06:29:36 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[06:29:36 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[06:29:36 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1399)
[06:29:36 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1234)
[06:29:36 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[06:29:36 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[06:29:36 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[06:29:36 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[06:29:36 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[06:29:36 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[06:29:36 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[06:29:36 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[06:29:36 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[06:29:36 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[06:29:36 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[06:29:36 ERROR]: #!#!
[06:29:36 ERROR]: #!#! Version Information:
[06:29:36 ERROR]: #!#!   Skript: 2.3-beta2 (latest)
[06:29:36 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[06:29:36 ERROR]: #!#!   Minecraft: 1.12.2
[06:29:36 ERROR]: #!#!   Java: 1.8.0_181 (Java HotSpot(TM) 64-Bit Server VM 25.181-b13)
[06:29:36 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[06:29:36 ERROR]: #!#!
[06:29:36 ERROR]: #!#! Server platform: Spigot
[06:29:36 ERROR]: #!#!
[06:29:36 ERROR]: #!#! Current node: set {_uuid} to network variable {api::users::%arg-2%::uuid} (api.sk, line 277)
[06:29:36 ERROR]: #!#! Current item: null
[06:29:36 ERROR]: #!#!
[06:29:36 ERROR]: #!#! Thread: Server thread
[06:29:36 ERROR]: #!#!
[06:29:36 ERROR]: #!#! Language: english
[06:29:36 ERROR]: #!#! Link parse mode: DISABLED
[06:29:36 ERROR]: #!#!
[06:29:36 ERROR]: #!#! End of Error.
[06:29:36 ERROR]: #!#!
```

**Comment by TheLimeGlass** [comment]
That looks like a problem with Skript, strange that it is happening in the init method.

Try downgrading or wait until the next beta version. NullPointers in Skript shouldn't happen.

**Comment by TheLimeGlass** [comment]
Potential duplicate https://github.com/TheLimeGlass/Skungee/issues/16
