### ISSUE TITLE
can't execute commands

### ISSUE THREAD

**Issue by ham1255** [TheLimeGlass/Skungee#30]
here
```
execute redis bungeecord console command "consolestaffchat %player% %arg 1%" on server "Lobby"
```
error
```
13:26:44 [SEVERE] Exception in thread "Thread-103" 
13:26:44 [SEVERE] java.lang.NoClassDefFoundError: com/imaginarycode/minecraft/redisbungee/RedisBungee
13:26:44 [SEVERE] 	at me.limeglass.skungee.bungeecord.handlers.SkungeePacketHandler.handlePacket(SkungeePacketHandler.java:332)
13:26:44 [SEVERE] 	at me.limeglass.skungee.bungeecord.sockets.SocketRunnable.run(SocketRunnable.java:95)
13:26:44 [SEVERE] 	at java.lang.Thread.run(Thread.java:748)
13:26:44 [SEVERE] Caused by: java.lang.ClassNotFoundException: com.imaginarycode.minecraft.redisbungee.RedisBungee
13:26:44 [SEVERE] 	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
13:26:44 [SEVERE] 	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
13:26:44 [SEVERE] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
13:26:44 [SEVERE] 	... 3 more
13:26:44 [SEVERE] Exception in thread "Thread-104" 
13:26:44 [SEVERE] java.lang.NoClassDefFoundError: com/imaginarycode/minecraft/redisbungee/RedisBungee
13:26:44 [SEVERE] 	at me.limeglass.skungee.bungeecord.handlers.SkungeePacketHandler.handlePacket(SkungeePacketHandler.java:332)
13:26:44 [SEVERE] 	at me.limeglass.skungee.bungeecord.sockets.SocketRunnable.run(SocketRunnable.java:95)
13:26:44 [SEVERE] 	at java.lang.Thread.run(Thread.java:748)
13:26:44 [SEVERE] Exception in thread "Thread-105" 
13:26:44 [SEVERE] java.lang.NoClassDefFoundError: com/imaginarycode/minecraft/redisbungee/RedisBungee
13:26:44 [SEVERE] 	at me.limeglass.skungee.bungeecord.handlers.SkungeePacketHandler.handlePacket(SkungeePacketHandler.java:332)
13:26:44 [SEVERE] 	at me.limeglass.skungee.bungeecord.sockets.SocketRunnable.run(SocketRunnable.java:95)
13:26:44 [SEVERE] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by TheLimeGlass** [comment]
You have to buy RedisBungee on Spigot or compile it off their GitHub.
