### ISSUE TITLE
A-Sync command dispatch error

### ISSUE THREAD

**Issue by ham1255** [TheLimeGlass/Skungee#37]
software: paper spigot 1.12.2
java 8
debian 9
error
```
[20:07:46 ERROR]: Command Dispatched Async: consolestaffchat Ham1255 hi
[20:07:46 ERROR]: Please notify author of plugin causing this execution to fix this bug! see: http://bit.ly/1oSiM6C
java.lang.Throwable: null
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:667) ~[patched_1.12.2.jar:git-Paper-1589]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:607) ~[patched_1.12.2.jar:git-Paper-1589]
        at ch.njol.skript.Skript.dispatchCommand(Skript.java:1267) ~[?:?]
        at ch.njol.skript.effects.EffCommand.execute(EffCommand.java:84) ~[?:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:52) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:57) ~[?:?]
        at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:152) ~[?:?]
        at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:110) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1589]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1589]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1589]
        at me.limeglass.skungee.spigot.sockets.SpigotPacketHandler.handlePacket(SpigotPacketHandler.java:193) ~[?:?]
        at me.limeglass.skungee.spigot.sockets.SpigotRunnable.run(SpigotRunnable.java:80) ~[?:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by TheLimeGlass** [comment]
Use the newest 1.0.7f version of Skungee.

**Comment by ham1255** [comment]
![image](https://user-images.githubusercontent.com/34905970/50099938-b1726880-0238-11e9-8a55-36a4e7c5f993.png)
it does keep erroring

**Comment by TheLimeGlass** [comment]
Are you using Skungee messages?

**Comment by ham1255** [comment]
yes

**Comment by ham1255** [comment]
.?

**Comment by TheLimeGlass** [comment]
Been addressed in next version.

**Comment by ham1255** [comment]
Okay thanks :)
