### ISSUE TITLE
Skungee Bungeecord crash

### ISSUE THREAD

**Issue by CarriedByMyClone** [TheLimeGlass/Skungee#4]
After a while, when the Bungeecord is launched Skungee makes it crash with a lot of mistakes as a result.

[07:58:30 INFO]: [Skungee]     at java.net.PlainSocketImpl.socketAccept(Native Method)
[07:58:30 INFO]: [Skungee]     at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
[07:58:30 INFO]: [Skungee]     at java.net.ServerSocket.implAccept(ServerSocket.java:545)
[07:58:30 INFO]: [Skungee]     at java.net.ServerSocket.accept(ServerSocket.java:513)
[07:58:30 INFO]: [Skungee]     at me.limeglass.skungee.bungeecord.Skungee$3.run(Skungee.java:108)
[07:58:30 INFO]: [Skungee]     at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
[07:58:30 INFO]: [Skungee]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[07:58:30 INFO]: [Skungee]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[07:58:30 INFO]: [Skungee]     at java.lang.Thread.run(Thread.java:748)
[07:58:30 INFO]:
[07:58:30 INFO]: [Skungee] Information:
[07:58:30 INFO]: [Skungee]   Skungee: 1.0.5
[07:58:30 INFO]: [Skungee]   Bungee: git:Waterfall-Bootstrap:1.12-SNAPSHOT:3b24d3f:172
[07:58:30 INFO]: [Skungee]   Game version: 1.8.x, 1.9.x, 1.10.x, 1.11.x, 1.12.x
[07:58:30 INFO]: [Skungee]   Protocol version: 340
[07:58:30 INFO]: [Skungee]   Java: 1.8.0_161 (Java HotSpot(TM) 64-Bit Server VM 25.161-b12)
[07:58:30 INFO]: [Skungee]   OS: Linux amd64 4.13.13-5-pve
[07:58:30 INFO]:
[07:58:30 INFO]: [Skungee] [Skungee] Severe Error:
[07:58:30 INFO]: [Skungee] Thread: Thread[Skungee Pool Thread #0,5,Skungee]
[07:58:30 INFO]: [Skungee] Socket couldn't be accepted.
> [07:58:30 INFO]:
[07:58:30 INFO]:
[07:58:30 INFO]: [Skungee] End of Error.
[07:58:30 INFO]:
[07:58:30 INFO]: [Skungee] Something went wrong within Skungee.
[07:58:30 INFO]: [Skungee] Please report this error to the developers of Skungee so we can fix this from happening in the future.
> [07:58:30 INFO]:
[07:58:30 INFO]: [Skungee] [Skungee] Severe Error:
[07:58:30 INFO]: [Skungee] Socket couldn't be accepted.
[07:58:30 INFO]:
[07:58:30 INFO]: [Skungee] Something went wrong within Skungee.
[07:58:30 INFO]: [Skungee] Please report this error to the developers of Skungee so we can fix this from happening in the future.
[07:58:30 INFO]:
[07:58:30 INFO]:
[07:58:30 INFO]: [Skungee] Please report this on the Skungee discussion page on SkUnity or Spigot. You can also message one of the Skungee developers.
[07:58:30 INFO]:
[07:58:30 INFO]: [Skungee] Stack trace:
[07:58:30 INFO]: [Skungee] java.net.SocketException: Too many open files (Accept failed)
[07:58:30 INFO]: [Skungee]     at java.net.PlainSocketImpl.socketAccept(Native Method)
[07:58:30 INFO]: [Skungee]     at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
[07:58:30 INFO]: [Skungee]     at java.net.ServerSocket.implAccept(ServerSocket.java:545)
[07:58:30 INFO]: [Skungee]     at java.net.ServerSocket.accept(ServerSocket.java:513)
[07:58:30 INFO]: [Skungee]     at me.limeglass.skungee.bungeecord.Skungee$3.run(Skungee.java:108)
[07:58:30 INFO]:
[07:58:30 INFO]: [Skungee] Thread: Thread[Skungee Pool Thread #0,5,Skungee]
[07:58:30 INFO]:
[07:58:30 INFO]: [Skungee] End of Error.
[07:58:30 INFO]:
[07:58:30 INFO]:
[07:58:30 INFO]: [Skungee] [Skungee] Severe Error:
[07:58:30 INFO]: [Skungee] Socket couldn't be accepted.
[07:58:30 INFO]:
[07:58:30 INFO]: [Skungee] Something went wrong within Skungee.
[07:58:30 INFO]: [Skungee] Please report this error to the developers of Skungee so we can fix this from happening in the future.
[07:58:30 INFO]:
[07:58:30 INFO]:
[07:58:30 INFO]: [Skungee] Please report this on the Skungee discussion page on SkUnity or Spigot. You can also message one of the Skungee developers.
[07:58:30 INFO]:
[07:58:30 INFO]: [Skungee] Stack trace:

I have this piece of error because it is spammed in loop all 1 tick I think... If people want to help me
Sorry for my English i'm French

**Comment by TheLimeGlass** [comment]
Try 1.0.5b and see if that fixes it

**Comment by CarriedByMyClone** [comment]
I put Skungee 1.0.5b on the Bungee or on all the servers + the Bungee?

**Comment by CarriedByMyClone** [comment]
I put it on Bungee, the error persists

**Comment by TheLimeGlass** [comment]
You put 1.0.5b on both Spigot and Bungeecord? They both need to be updated.

**Comment by TheLimeGlass** [comment]
Can you also try with Spigot's Bungeecord and not Waterfall. I have not tested with Waterfall.

**Comment by TheLimeGlass** [comment]
Can you try 1.0.5d and see if this error is fixed?

**Comment by TheLimeGlass** [comment]
Closing until further information is provided.
