### ISSUE TITLE
Support for the Spigot Version 1.13.2

### ISSUE THREAD

**Issue by Tyberhertz** [TheLimeGlass/Skungee#41]
[08:42:02] [Server thread/INFO]: [Skungee] Enabling Skungee v1.0.9*
[08:42:04] [Server thread/ERROR]: Error occurred while enabling Skungee v1.0.9 (Is it up to date?)
java.lang.NullPointerException: null
	at me.limeglass.skungee.spigot.sockets.Sockets.connect(Sockets.java:78) ~[?:?]
	at me.limeglass.skungee.spigot.Skungee.onEnable(Skungee.java:81) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-476]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.2.jar:git-Paper-476]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-476]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-476]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-476]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[patched_1.13.2.jar:git-Paper-476]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[patched_1.13.2.jar:git-Paper-476]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[patched_1.13.2.jar:git-Paper-476]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-476]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-476]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[08:42:04] [Server thread/INFO]: [Skungee] Disabling Skungee v1.0.9

**Comment by TheLimeGlass** [comment]
Try restarting the server

**Comment by Tyberhertz** [comment]
I have the Prox and the Spigot server restartet:

This is the error code of the Proxy (Bungeecord)

[11:13:48] [Thread-13/INFO]: [Skungee] Connected to server Server1 with port 25561
[11:13:48] [Thread-14/INFO]: 
[11:13:48] [Thread-14/INFO]: [Skungee] [Skungee] Severe Error: [Unknown host: /127.0.0.1:25561]
[11:13:48] [Thread-14/INFO]: 
[11:13:48] [Thread-14/INFO]: [Skungee] Something went wrong within Skungee.
[11:13:48] [Thread-14/INFO]: [Skungee] Please report this error to the developers of Skungee so we can fix this from happening in the future.
[11:13:48] [Thread-14/INFO]: 
[11:13:48] [Thread-14/INFO]: [Skungee] Report this at https://github.com/TheLimeGlass/Skungee/issues. You can also message one of the Skungee developers.
[11:13:48] [Thread-14/INFO]: 
[11:13:48] [Thread-14/INFO]: [Skungee] Stack trace:
[11:13:48] [Thread-14/INFO]: [Skungee] java.net.UnknownHostException: Minecraft-Server: Minecraft-Server: Name or service not known
[11:13:48] [Thread-14/INFO]: [Skungee]     at java.net.InetAddress.getLocalHost(InetAddress.java:1506)
[11:13:48] [Thread-14/INFO]: [Skungee]     at me.limeglass.skungee.bungeecord.handlers.HeartbeatHandler.handlePacket(HeartbeatHandler.java:30)
[11:13:48] [Thread-14/INFO]: [Skungee]     at me.limeglass.skungee.bungeecord.handlercontroller.SkungeeHandler.callPacket(SkungeeHandler.java:98)
[11:13:48] [Thread-14/INFO]: [Skungee]     at me.limeglass.skungee.bungeecord.sockets.BungeeRunnable.run(BungeeRunnable.java:92)
[11:13:48] [Thread-14/INFO]: [Skungee]     at java.lang.Thread.run(Thread.java:748)
[11:13:48] [Thread-14/INFO]: [Skungee] Caused by: java.net.UnknownHostException: Minecraft-Server: Name or service not known
[11:13:48] [Thread-14/INFO]: [Skungee]     at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
[11:13:48] [Thread-14/INFO]: [Skungee]     at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
[11:13:48] [Thread-14/INFO]: [Skungee]     at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
[11:13:48] [Thread-14/INFO]: [Skungee]     at java.net.InetAddress.getLocalHost(InetAddress.java:1501)
[11:13:48] [Thread-14/INFO]: [Skungee]     at me.limeglass.skungee.bungeecord.handlers.HeartbeatHandler.handlePacket(HeartbeatHandler.java:30)
[11:13:48] [Thread-14/INFO]: [Skungee]     at me.limeglass.skungee.bungeecord.handlercontroller.SkungeeHandler.callPacket(SkungeeHandler.java:98)
[11:13:48] [Thread-14/INFO]: [Skungee]     at me.limeglass.skungee.bungeecord.sockets.BungeeRunnable.run(BungeeRunnable.java:92)
[11:13:48] [Thread-14/INFO]: [Skungee]     at java.lang.Thread.run(Thread.java:748)
[11:13:48] [Thread-14/INFO]: 
[11:13:48] [Thread-14/INFO]: [Skungee] Information:
[11:13:48] [Thread-14/INFO]: [Skungee]   Skungee: 1.0.9
[11:13:48] [Thread-14/INFO]: [Skungee]   Bungee: git:BungeeCord-Bootstrap:1.13-SNAPSHOT:afef0ec:1374
[11:13:48] [Thread-14/INFO]: [Skungee]   Game version: 1.8.x-1.13.x
[11:13:48] [Thread-14/INFO]: [Skungee]   Protocol version: 404
[11:13:48] [Thread-14/INFO]: [Skungee]   Java: 1.8.0_191 (OpenJDK 64-Bit Server VM 25.191-b12)
[11:13:48] [Thread-14/INFO]: [Skungee]   OS: Linux amd64 4.4.59+
[11:13:48] [Thread-14/INFO]: 
[11:13:48] [Thread-14/INFO]: [Skungee] Thread: Thread[Thread-14,5,Skungee]
[11:13:48] [Thread-14/INFO]: [Skungee] Cause: [Unknown host: /127.0.0.1:25561]
[11:13:48] [Thread-14/INFO]: 
[11:13:48] [Thread-14/INFO]: [Skungee] End of Error.

**Comment by TheLimeGlass** [comment]
The host was not found, try using "localhost" or the actual ip for the IP option.

**Comment by Tyberhertz** [comment]
I solved the problem with another server.
