### ISSUE TITLE
ServerIntance

### ISSUE THREAD

**Issue by Gommzy** [TheLimeGlass/Skungee#49]
I bought the Addon ServerIntance for SKungee and get this error:

Could not load plugin from file plugins/Skungee/ServerInstances.jar
java.lang.NullPointerException
    at net.md_5.bungee.api.plugin.PluginManager.detectPlugins(PluginManager.java:353)
    at me.limeglass.skungee.bungeecord.serverinstances.Premium.check(Premium.java:21)
    at me.limeglass.skungee.bungeecord.Skungee.onEnable(Skungee.java:56)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:226)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:280)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

Thank you :smile:

**Comment by TheLimeGlass** [comment]
I said this on Discord, will copy.

You can just place the ServerInstances jar like a normal plugin. Doesn't have to be in the Skungee folder, also make sure it's going on the Bungeecord.

**Comment by Gommzy** [comment]
Error enabling plugin ServerInstances
java.lang.NoClassDefFoundError: me/limeglass/skungee/bungeecord/BungecordMetrics$CustomChart
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
    at java.lang.Class.getConstructor0(Class.java:3075)
    at java.lang.Class.getDeclaredConstructor(Class.java:2178)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:304)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:211)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:266)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: me.limeglass.skungee.bungeecord.BungecordMetrics$CustomChart
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 9 more

**Comment by Gommzy** [comment]
This error is in the bungeecord plugins folder

**Comment by TheLimeGlass** [comment]
You need to have Skungee installed, check the Skungee thread on how to set it up

https://forums.skunity.com/resources/skungee-1-bungeecord-addon-for-skript.87/

**Comment by Gommzy** [comment]
Skungee is right installed. Alle network variables work.

**Comment by Gommzy** [comment]
12:34:37 [WARNUNG] Error enabling plugin ServerInstances
java.lang.NoClassDefFoundError: me/limeglass/skungee/bungeecord/BungecordMetrics$CustomChart
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
    at java.lang.Class.getConstructor0(Class.java:3075)
    at java.lang.Class.getDeclaredConstructor(Class.java:2178)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:304)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:211)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:266)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: me.limeglass.skungee.bungeecord.BungecordMetrics$CustomChart
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 9 more

**Comment by Gommzy** [comment]
Version: git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5ef4dd2:1387 by md_5

**Comment by TheLimeGlass** [comment]
Try reinstalling Skungee

**Comment by Gommzy** [comment]
don't work :(

**Comment by TheLimeGlass** [comment]
The ServerInstances.jar is not within the Skungee folder right? Make sure the only jar of ServerInstances.jar, is in the plugins folder on Bungeecord.
