### ISSUE TITLE
Skellett refuses to connect to Skungee

### ISSUE THREAD

**Issue by diamondpumpkin** [TheLimeGlass/Skungee#50]
Minecraft: 1.13.2
BungeeCord: 1396
Skungee: 1.0.8, 1.0.9 & 1.0.9a
Skellet: 1.9.6b

Issue:
Installed Skungee and Skellett, configured both to run on the correct ports. Skellett server refuses to connect on localhost, so I tried 0.0.0.0, 127.0.0.1 and my server's public IP. None worked, all threw this error
```
07.02 14:55:42 [Server] INFO [Skellett] Incorrect SkellettProxy details, No socket found or was denied access. For socket at 63.141.238.34:1337
07.02 14:55:42 [Server] ERROR [Skript] If you're 100% sure your details are correct, this can be caused because some server's want a number host rather than localhost. Try inserting 0.0.0.0 or 127.0.0.1 instead of localhost. Error: 
07.02 14:55:42 [Server] INFO [Skellett] Attempting to reconnect and fix myself...
07.02 14:55:42 [Server] WARN java.io.EOFException
07.02 14:55:42 [Server] WARN at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2960)
07.02 14:55:42 [Server] WARN at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1540)
07.02 14:55:42 [Server] WARN at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
07.02 14:55:42 [Server] WARN at com.gmail.thelimeglass.Sockets.connect(Sockets.java:69)
07.02 14:55:42 [Server] WARN at com.gmail.thelimeglass.Sockets$1.run(Sockets.java:27)
07.02 14:55:42 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
07.02 14:55:42 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392)
07.02 14:55:42 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889)
07.02 14:55:42 [Server] WARN at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
07.02 14:55:42 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
07.02 14:55:42 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
07.02 14:55:42 [Server] WARN at java.lang.Thread.run(Thread.java:748)
07.02 14:55:42 [Server] WARN java.net.BindException: Address already in use (Bind failed)
07.02 14:55:42 [Server] WARN at java.net.PlainSocketImpl.socketBind(Native Method)
07.02 14:55:42 [Server] WARN at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
07.02 14:55:42 [Server] WARN at java.net.ServerSocket.bind(ServerSocket.java:375)
07.02 14:55:42 [Server] WARN at java.net.ServerSocket.<init>(ServerSocket.java:237)
07.02 14:55:42 [Server] WARN at java.net.ServerSocket.<init>(ServerSocket.java:128)
07.02 14:55:42 [Server] WARN at com.gmail.thelimeglass.Sockets$1$1.run(Sockets.java:34)
07.02 14:55:42 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
07.02 14:55:42 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
07.02 14:55:42 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
07.02 14:55:42 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
07.02 14:55:42 [Server] WARN at java.lang.Thread.run(Thread.java:748)
```
Also tried on port 7801
```
07.02 15:04:06 [Server] INFO [Skellett] SkellettProxy connection established on port 7800
07.02 15:04:06 [Server] INFO [Skellett] Incorrect SkellettProxy details, No socket found or was denied access. For socket at 0.0.0.0:7801
07.02 15:04:06 [Server] ERROR [Skript] If you're 100% sure your details are correct, this can be caused because some server's want a number host rather than localhost. Try inserting 0.0.0.0 or 127.0.0.1 instead of localhost. Error: 
07.02 15:04:06 [Server] INFO [Skellett] Attempting to reconnect and fix myself...
07.02 15:04:06 [Server] INFO [Skellett] Bungeecord went offline. Attempting to reconnect...
07.02 15:04:06 [Server] WARN java.io.EOFException
07.02 15:04:06 [Server] WARN at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2960)
07.02 15:04:06 [Server] WARN at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1540)
07.02 15:04:06 [Server] WARN at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
07.02 15:04:06 [Server] WARN at com.gmail.thelimeglass.Sockets.connect(Sockets.java:69)
07.02 15:04:06 [Server] WARN at com.gmail.thelimeglass.Sockets$1.run(Sockets.java:27)
07.02 15:04:06 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
07.02 15:04:06 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392)
07.02 15:04:06 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889)
07.02 15:04:06 [Server] WARN at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
07.02 15:04:06 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
07.02 15:04:06 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
07.02 15:04:06 [Server] WARN at java.lang.Thread.run(Thread.java:748)
07.02 15:04:06 [Server] INFO [Skellett] SkellettProxy connection established on port 7800
07.02 15:04:06 [Server] INFO [Skellett] Incorrect SkellettProxy details, No socket found or was denied access. For socket at 0.0.0.0:7801
```

the Bungee server and it's child servers are all on the same machine, no configurations work. Is this project abandoned? Doesn't seem to work well.

**Comment by TheLimeGlass** [comment]
SkellettProxy is not Skungee, Skungee is a universal plugin for both Spigot and Bungeecord. Set the SkellettProxy option to false and use Skungee on the Spigot servers. The main Skungee thread tells you all about how to setup Skungee.

**Comment by diamondpumpkin** [comment]
How about you make that clear in your posts?
"Oh yeah, this IS NOT SkelletProxy and has a different installation method."
Instead of making yourself look like a dumbass.
https://imgur.com/a/4AJ9Bqg
