### ISSUE TITLE
Null pointer in the new ping event

### ISSUE THREAD

**Issue by TheLimeGlass** [TheLimeGlass/Skungee#6]
```
01:43:48 [WARNING] Error pinging remote server
io.netty.channel.AbstractChannel$AnnotatedConnectException: syscall:getsockopt(..) failed: Connection refused: /139.99.161.154:25565
	at io.netty.channel.unix.Socket.finishConnect(..)(Unknown Source)
Caused by: io.netty.channel.unix.Errors$NativeConnectException: syscall:getsockopt(..) failed: Connection refused
	... 1 more
01:43:48 [SEVERE] May 25, 2018 1:43:48 AM net.md_5.bungee.event.EventBus post
WARNING: Error dispatching event ProxyPingEvent(connection=[/70.73.21.149:49456] <-> InitialHandler, response=ServerPing(version=null, players=null, description=§f§c[Bungee] Cant connect to server., modinfo=ServerPing.ModInfo(type=FML, modList=[]))) to listener me.limeglass.skungee.bungeecord.listeners.EventListener@2e55dd0c
java.lang.NullPointerException
	at me.limeglass.skungee.bungeecord.listeners.EventListener.onPing(EventListener.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
	at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:377)
	at net.md_5.bungee.connection.InitialHandler$3.done(InitialHandler.java:230)
	at net.md_5.bungee.connection.InitialHandler$3.done(InitialHandler.java:209)
	at net.md_5.bungee.BungeeServerInfo$1.operationComplete(BungeeServerInfo.java:139)
	at net.md_5.bungee.BungeeServerInfo$1.operationComplete(BungeeServerInfo.java:130)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:512)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:505)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:484)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:425)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.fulfillConnectPromise(AbstractEpollChannel.java:633)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:652)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:526)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by TheLimeGlass** [comment]
Actually I think this was fixed but not tested. TODO test.
