### ISSUE TITLE
Exception on plugin load

### ISSUE THREAD

**Issue by joshwenke** [TheLimeGlass/Skungee#7]
This is on Bungee. 

15:57:24 [WARNING] Exception encountered when loading plugin: Skungee
java.lang.NullPointerException
    at me.limeglass.skungee.bungeecord.Skungee.consoleMessage(Skungee.java:246)
    at me.limeglass.skungee.bungeecord.Skungee.loadConfiguration(Skungee.java:88)
    at me.limeglass.skungee.bungeecord.Skungee.onEnable(Skungee.java:49)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:266)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by TheLimeGlass** [comment]
Delete configuration and make sure anything viewing it has been closed, then restart the server.
