### ISSUE TITLE
RedisBungee throwing Class Not Found exception

### ISSUE THREAD

**Issue by JDHallows** [TheLimeGlass/Skungee#9]
The following Skript is throwing a Class Not Found exception for RedisBungee. Not sure what the issue is, since it was working fine a few days ago and I don't believe I have changed anything since then.
```
command /test:
	trigger:
		set {bungeecmd} to "say Testing"
		execute redis-bungeecord console command {bungeecmd} on the server "public"
```

```
14:14:48 [SEVERE] Exception in thread "Thread-75"
14:14:48 [SEVERE] java.lang.NoClassDefFoundError: com/imaginarycode/minecraft/redisbungee/RedisBungee
14:14:48 [SEVERE]     at me.limeglass.skungee.bungeecord.sockets.PacketHandler.handlePacket(PacketHandler.java:553)
14:14:48 [SEVERE]     at me.limeglass.skungee.bungeecord.sockets.SocketRunnable.run(SocketRunnable.java:81)
14:14:48 [SEVERE]     at java.lang.Thread.run(Thread.java:748)
14:14:48 [SEVERE] Caused by: java.lang.ClassNotFoundException: com.imaginarycode.minecraft.redisbungee.RedisBungee
14:14:48 [SEVERE]     at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
14:14:48 [SEVERE]     at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
14:14:48 [SEVERE]     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
14:14:48 [SEVERE]     ... 3 more
```

**Comment by TheLimeGlass** [comment]
This issue is caused when RedisBungee is not in the runtime of Bungeecord, so Skungee can't find the class. Make sure it's properly installed and enabled, also make sure you're using the latest Spigot, Bungeecord, Redis and RedisBungee. The issue most likely relies in RedisBungee either not enabling or not being installed. There may have been a new RedisBungee update if it has an auto updater.
